### ISSUE TITLE
Visualization code/tutorials (gif)

### ISSUE THREAD

**Issue by rayarit** [gorkaydemir/ADAPT#2]
Can you please upload visualization code what is present in your [website](https://kuis-ai.github.io/adapt/#:~:text=However%2C%20existing%20methods%20for%20trajectory,scene%20with%20dynamic%20weight%20learning)  .

**Comment by gorkaydemir** [comment]
Hi, I just uploaded a notebook to `utils/` folder for both visualizations in gif and image. I hope it helps.
