### ISSUE TITLE
code for the interaction dataset

### ISSUE THREAD

**Issue by linaashaji** [gorkaydemir/ADAPT#3]
Hello,

Thanks for your work. Will you share the code regarding the preprocessing of the interaction dataset?

**Comment by gorkaydemir** [comment]
Hi,
Sorry for the late reply. 
I followed the preprocessing steps of the Autobot paper for the Interaction dataset, explained here: https://github.com/roggirg/AutoBots/tree/master/datasets/interaction_dataset

Best
