### ISSUE TITLE
failed to get onnx model

### ISSUE THREAD

**Issue by MichaelH717** [gorkaydemir/ADAPT#4]
Hello,

Thanks for your work, when i convert  model to onnx, only this bug report:

  >>Process finished with exit code 136 (interrupted by signal 8:SIGFPE)
have you meet this problem?

**Comment by gorkaydemir** [comment]
Hi, sorry for the late reply.

Unfortunately, I haven't converted the model to ONNX, so I haven't encountered this issue before.

Best

**Comment by MichaelH717** [comment]
> Hi, sorry for the late reply.
> 
> Unfortunately, I haven't converted the model to ONNX, so I haven't encountered this issue before.
> 
> Best

ok, thanks!
