### ISSUE TITLE
"information_matrix" and "pos_matrix" in argoverse_dataset.py

### ISSUE THREAD

**Issue by HUXING8** [gorkaydemir/ADAPT#6]
the file _argoverse_dataset.py_ shows the process of ex_file. It gets _mapping_ from the processed file which is used in DenseTNT, but there is no "information_matrix" or "pos_matrix" dict key in the _mapping_.

**Comment by gorkaydemir** [comment]
Hi,
The preprocessing of the DenseTNT is modified. You need to extract the ex_list files following the steps in the `ADAPT/dataset/`. You can find how the `information_matrix` and `pos_matrix` are extracted, in the [preprocess script](https://github.com/gorkaydemir/ADAPT/blob/2c9ec0918fe5c0541e1e6acd0c888cf170702368/dataset/preprocess_data.py#L360).

Best
